### ISSUE TITLE
Fill correct metadata to meta/

### ISSUE THREAD

**Issue by dasJ** [stuvusIT/zammad#3]
See Vault role for example

**Comment by Scriptkiddi** [comment]
this is not a issue description, please paste what you mean in here next time

**Comment by Scriptkiddi** [comment]
should be fixed with new pull request

**Comment by dasJ** [comment]
No.

**Comment by Scriptkiddi** [comment]
no is not an awnser that i can work with please state what your issue is

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 240 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 247 days.
